actionitems/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='action_item_index'),
    path('list/<str:as_a>/<str:status>', views.list_by_status, name='action_item_list'),
    path('<int:action_item_id>/', views.action_item, name='action_item'),
    path('create', views.action_item_create, name='action_item_create_select'),
    path('create/<int:template_id>', views.action_item_create, name='action_item_create'),
    path('<int:action_item_id>/edit', views.action_item_edit, name='action_item_edit'),
    path('<int:action_item_id>/close', views.action_item_close, name='action_item_close'), # one button to close action item with confirmaton and delete all related reminder
    path('<int:action_item_id>/propose-close', views.action_item_propose_close, name='action_item_propose_close'), # one button to propose close, with conformation and add remarks
    # path('<int:action_item_id>/change-due-date', views.action_item_change_due_date, name='action_item_change_date'), # one button to change due date
    path('<int:action_item_id>/reminder/add', views.reminder_add, name='reminder_add'),
    path('<int:action_item_id>/delete/<int:update_id>', views.update_delete, name='update_delete'),
    # search by template name - for searching details that is not in the main model
    path('template/', views.template_index, name='template_index'),
    path('template/<int:template_id>/download-csv', views.template_csv_dl, name='template_csv_dl'),
    path('template/<int:template_id>/upload-csv', views.template_csv_ul, name='template_csv_ul'),

]

simpleair/urls.py
from django.contrib import admin
from django.urls import include,path
from django.http import HttpResponse

urlpatterns = [
    path('',include('user.urls')),
    path('app/', include('actionitems.urls')),
    path('admin/', admin.site.urls),
    path('robots.txt', lambda x: HttpResponse("User-Agent: *\nDisallow: /app/\nDisallow: /user/", content_type="text/plain"), name="robots_file"),
]

user/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views
from django.http import HttpResponseRedirect
from django.shortcuts import reverse
from user.forms import AuthenticationFormExtra, PasswordResetFormExtra, SetPasswordFormExtra

urlpatterns = [
    path('', views.index, name="index"),
    
    path('login/', auth_views.LoginView.as_view(
        template_name='user/login.html',
        authentication_form=AuthenticationFormExtra,
    ), name='login'),
    
    path('user/logout/', auth_views.LogoutView.as_view(), name="logout"),
    
    path('user/password-change/', views.change_password, name="password_change"),
    
    path('user/password-reset/', auth_views.PasswordResetView.as_view(
        template_name='user/reset.html',
        form_class=PasswordResetFormExtra,
    ), name='password_reset'),

    path('user/password-reset/done/',auth_views.PasswordResetView.as_view(
        template_name='user/reset.html',
        form_class=PasswordResetFormExtra,
        extra_context={
            'alert_success':'Password reset successful, We\'ve e-mailed you instructions for setting your password to the e-mail address you submitted. You should be receiving it shortly.'
        },
    ), name='password_reset_done'),
    
    path('user/password-reset/reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='user/change_password.html',
        form_class=SetPasswordFormExtra,
    ),name='password_reset_confirm'),
    
    # path('user/password-reset/', auth_views.PasswordResetCompleteView.as_view(
    #     template_name='user/reset.html',
    # ), name='password_reset_complete'),

    path('user/password-reset/login', auth_views.LoginView.as_view(
        template_name='user/login.html',
        authentication_form=AuthenticationFormExtra,
        extra_context={'alert_success':'Password reset completed, please login with your new password'},
    ), name='password_reset_complete'),
]

actionitems/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField, ArrayField
from django.contrib.auth.models import User
from user.models import Department, Company
from datetime import date
from django.utils import timezone
import json

class Template(models.Model):
    """ Template is the template for details required and default settings for the action item(Item) """
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=300, blank=True)
    # CASCADE means if the user is deleted, all the template under it will also be deleted
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    # schema and options will rely heavily on alpacajs
    schema = JSONField()
    options = JSONField()
    # other settings
    settings = JSONField(default=dict())

    company = models.ForeignKey(
        Company,
        on_delete=models.CASCADE,
    )

    @property
    def get_json_data(self):
        return json.dumps(self.data)

    def __str__(self):
        return self.name

def get_sentinel_user():
    return get_user_model().objects.get_or_create(username='deleted')[0]

class ActionItem(models.Model):
    """ Item model is the action item, that follows the template it is related to """
    
    title = models.CharField(max_length=100)
    finding = models.TextField(blank=True)
    smart_action_item = models.TextField(blank=True)

    # CASCADE means if the template is deleted, all the action items under it will also be deleted
    template = models.ForeignKey(
        Template,
        on_delete=models.CASCADE,
    )

    CLASSIFICATION_CHOICES = (
        ('L','Low/ OFI'),
        ('M','Medium'),
        ('H','High'),
        ('VH','Very High/ Serious/ NCR'),
    )
    classification = models.CharField(max_length=2,choices=CLASSIFICATION_CHOICES,default='M')

    # date that the item is first published
    published_date = models.DateTimeField(auto_now_add=True)
    # date that shows the last modified date
    last_modified_date = models.DateTimeField(auto_now=True)
    # due date is the agreed date to complete the action item
    due_date = models.DateTimeField()
    @property
    def is_past_due(self):
        if timezone.now().date() > self.due_date.date():
            return True
        return False
    
    # a JSON of all the custom details for the form
    details = JSONField(default=dict())

    # auto put at the person who created the item
    creator = models.ForeignKey(
        User,
        on_delete=models.SET(get_sentinel_user),
        related_name='creator'
    )

    # a group of people who is interested of the action item
    initiator = models.ManyToManyField(
        User,
        related_name='initiator'
    )

    # a group of people who owns the action item
    owner = models.ManyToManyField(
        User,
        related_name='owner',
        blank=True,
    )

    # a group of people who is assigned the action item
    assignee = models.ManyToManyField(
        User,
        related_name='assignee',
    )

    department = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
    )

    # make a button if the assignee or owner wants to propose to complete, just push a button with warning
    STATUS_CHOICES = (
        ('OPEN', 'Open'),
        ('OVERDUE', 'Overdue'),
        ('PROPOSE-CLOSE', 'Proposed to close'),
        ('COMPLETED','Completed'),
    )
    status = models.CharField(max_length=20,choices=STATUS_CHOICES, default="OPEN")

    def __str__(self):
        return "%s: %s" % (self.title, self.id)

class Update(models.Model):
    """ This is a section in Item where the action item assignee, owner, and creator can put remarks/progress updates"""
    # if the User is deleted, it will create or use the 'deleted' username
    user = models.ForeignKey(
        User,
        on_delete=models.SET(get_sentinel_user),
    )
    # CASCADE means if item is deleted, the correspoding update will be deleted as well
    action_item = models.ForeignKey(
        ActionItem,
        on_delete=models.CASCADE,
    )
    text = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s: %s" % (self.user, self.text)

class Reminder(models.Model):
    """ This is a section in Item where the reminder email should be triggered for an Item"""
    # CASCADE means if item is deleted, the correspoding reminder will be deleted as well
    action_item = models.ForeignKey(
        ActionItem,
        on_delete=models.CASCADE,
    )
    reminder_date = models.DateTimeField()
    is_triggered = models.BooleanField(default=False)

    @property
    def is_past_due(self):
        if timezone.now().date() > self.reminder_date.date():
            return True
        return False

    def __str__(self):
        return "(%s) %s: %s" % (self.id, self.reminder_date, self.action_item.title)

actionitems/forms.py
from django import forms
from django.contrib.postgres.forms import SplitArrayField,SimpleArrayField
from django.urls import reverse
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Button, Submit, HTML, Field, Div, Hidden
from user.models import Company, Department
from .models import ActionItem, Update, Reminder
from django.forms import modelformset_factory

class ActionItemForm(forms.ModelForm):

    class Meta:
        model = ActionItem
        fields = [
            'title', 
            'finding', 
            'smart_action_item',
            'classification',
            # 'status',
            'due_date',
            'initiator',
            'owner',
            'assignee',
            'department',
        ]

    
    def __init__(self, *args, **kwargs):
        company = kwargs.pop('company', None)
        super(ActionItemForm, self).__init__(*args, **kwargs)
        if company:
            self.fields['initiator'].queryset = User.objects.filter(profile__company__id=company.id)
            self.fields['owner'].queryset = User.objects.filter(profile__company__id=company.id)
            self.fields['assignee'].queryset = User.objects.filter(profile__company__id=company.id)
            self.fields['department'].queryset = Department.objects.filter(company__id=company.id)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Submit'))
        self.helper.layout = Layout(
            Field('title'),
            Field('finding'),
            Field('smart_action_item'),
            Field('due_date'),
            Field('classification'),
            Field('status'),
            Field('department'),
            Field('initiator', css_class='selectpicker'),
            Field('owner', css_class='selectpicker'),
            Field('assignee', css_class='selectpicker'),
            HTML(
                "<div id=\"details\"></div>"
            )
        )
    
    title = forms.CharField(
        label = "Title",
        required = True,
    )

    finding = forms.CharField(
        widget = forms.Textarea(
            attrs={'rows':4, 'cols':15}),
        required=False,
        help_text = "Detail issues/area of concern",
    )

    smart_action_item = forms.CharField(
        widget = forms.Textarea(
            attrs={'rows':4, 'cols':15}),
        required=False,
        help_text = "Detail information on the action item using SMART",
    )

    class MyModelMultipleChoiceField(forms.ModelMultipleChoiceField):
        def label_from_instance(self, obj):
            return "%s (%s)" % (obj.profile.full_name, obj.username)

    
    initiator = MyModelMultipleChoiceField(
        widget = forms.SelectMultiple(
            attrs = {"data-live-search":"true"},
        ),
        queryset = User.objects.all(),
    )

    owner = MyModelMultipleChoiceField(
        widget = forms.SelectMultiple(
            attrs = {"data-live-search":"true"},
        ),
        required=False,
        queryset = User.objects.all(),
    )

    assignee = MyModelMultipleChoiceField(
        widget = forms.SelectMultiple(
            attrs = {"data-live-search":"true"},
        ),
        queryset = User.objects.all(),
    )

    department = forms.ModelChoiceField(
        queryset = Department.objects.all(),
    )
    
    due_date = forms.DateTimeField(
        label = "Due Date",
        required = True,
    )

    # status = forms.ChoiceField(
    #     choices = ActionItem.STATUS_CHOICES,
    # )

    classification = forms.ChoiceField(
        choices = ActionItem.CLASSIFICATION_CHOICES,
    )

class ActionItemStatusForm(forms.ModelForm):

    class Meta:
        model = ActionItem
        fields = [
            'status',
        ]

    status = forms.ChoiceField(
        choices = ActionItem.STATUS_CHOICES,
    )

class UpdateForm(forms.ModelForm):

    class Meta: 
        model = Update
        fields = ['text']

    def __init__(self, *args, **kwargs):
        super(UpdateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Submit'))
        self.helper.layout = Layout(
            Field('text'),
            HTML("<p> by {{ user.profile.full_name }}</p>"),
        )

    text = forms.CharField(
        label = '',
        widget=forms.Textarea(
            attrs={'rows':4, 'cols':15, 'placeholder':'Add your update/remarks'}),
    )

class ReminderForm(forms.ModelForm):

    class Meta: 
        model = Reminder
        fields = ['reminder_date']

    reminder_date = forms.DateTimeField(
        label = '',
        widget = forms.DateTimeInput(
            attrs={"placeholder":"Set date for reminder"}
        )
    )

    # action_item = forms.ModelChoiceField(
    #     queryset = ActionItem.objects.all(),
    # )


class ReminderFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(ReminderFormSetHelper, self).__init__(*args, **kwargs)
        self.form_method = 'post'
        # self.add_input(Button('minus', '- row', css_class='btn btn-warning'))
        self.add_input(Button('add', '+ row', css_class='btn btn-default'))
        self.form_show_labels = False
        self.add_input(Submit('submit', 'Submit', css_class='pull-right', onclick="goBack()"))
        self.layout = Layout(
            Div(
                Div(
                    Field('reminder_date'),
                    HTML("<input type=hidden name='form-{{ forloop.counter0 }}-DELETE' value=''>"),
                    css_class="col-sm-10",
                ),
                Div(
                    HTML("<button name='{{ forloop.counter0 }}-DELETE' class='close pull-left' type='button'> &times; </button>"),
                    css_class="col-sm-2",
                ),
                css_class="row datepicker-set",
            )
        )
        self.render_required_fields = True

actionitems/templates/actionitems/action_item.html
{% extends "actionitems/base.html" %}

{% block main %}

{% if action_item %}
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="section">
                <h2 class="text-center">{{ action_item.title }}</h2>
        </div>
    </div>
</div>
<div class="row">
<div class="col-md-6 col-md-offset-1">
    <div class="section">
            <h3>Details</h3>
            <div class="panel panel-default">
                <div class="panel-body">
                    {% comment %} to make each status different color {% endcomment %}
                    <p>Title: {{ action_item.title }}</p>
                    <p>Status: 
                        {% if action_item.status == "OPEN" %}
                            <span class="bg-warning">{{ action_item.get_status_display }}</span>
                        {% elif action_item.status == "OVERDUE"  %}
                            <span class="bg-danger">{{ action_item.get_status_display }}</span>
                        {% elif action_item.status == "PROPOSE-CLOSE"  %}
                            <span class="bg-info">{{ action_item.get_status_display }}</span>
                        {% elif action_item.status == "COMPLETED"  %}
                            <span class="bg-success">{{ action_item.get_status_display }}</span>
                        {% endif %}
                    
                    </p>
                    <p>Classification: {{ action_item.get_classification_display }} </p>
                    <p>Due date: {{ action_item.due_date|date:"j M Y" }}
                        {% if action_item.status == "OPEN" %} 
                        ({{ action_item.due_date|timeuntil }} to due date)
                        {% elif action_item.status == "OVERDUE"  %}
                        ({{ action_item.due_date|timesince }} past due date)
                        {% endif %}
                    </p>
                    <p>Department: {{ action_item.department.name }}</p>
                    {% if action_item.finding %}
                        <p>Finding:</p>
                        <p>{{ action_item.finding }}</p>
                    {% endif %}
                    {% if action_item.smart_action_item %}
                        <p>SMART Action Item:</p>
                        <p>{{ action_item.smart_action_item }}</p>
                    {% endif %}
                    {% comment %} to fix details name in template, no dash {% endcomment %}
                    {% for k,v in action_item.details.items %}
                    <p>{{ k|capfirst }}:
                            {% if v %}
                                {{ v|capfirst }}
                            {% else %}
                                -
                            {% endif %}
                        </p>
                    {% endfor %}
                    <hr>
                    <p>Initiator:
                        <ul>
                            {% for user in action_item.initiator.all %}
                            <li>{{ user.profile.full_name }}, {{ user.email }}</li>
                            {% empty %} - {% endfor %}
                        </ul>
                    
                    </p>
                    <p>Owner:
                        <ul>
                            {% for user in action_item.owner.all %}
                            <li>{{ user.profile.full_name }}, {{ user.email }}</li>
                            {% empty %} - {% endfor %}
                        </ul>
                    </p>
                    <p>Assignee:
                        <ul>
                            {% for user in action_item.assignee.all %}
                            <li>{{ user.profile.full_name }}, {{ user.email }}</li>
                            {% empty %} - {% endfor %}
                        </ul>
                    </p>
                    <hr>
                    {% if reminder %}
                        <a class="btn btn-sm btn-default" role="button" data-toggle="collapse" 
                        href="#collapseReminder" aria-expanded="false" aria-controls="collapseReminder">Show Reminder</a>
                        <div class="collapse" id="collapseReminder">
                            <div class="well well-sm">
                                    {% for r in reminder|dictsort:"reminder_date" %}
                                        {% if r.is_triggered %}
                                            <p>Reminder {{ forloop.counter }} -  
                                                {{ r.reminder_date|date:"j M Y" }} was triggered.
                                            </p>                                        
                                        {% else %}
                                        <p>Reminder {{ forloop.counter }} -
                                            {% if r.is_past_due %}
                                                {{ r.reminder_date|date:"j M Y" }} was not triggered. 
                                            {% else %}
                                                {{ r.reminder_date|date:"j M Y" }} 
                                                will trigger in {{ r.reminder_date|timeuntil }}
                                            {% endif %}
                                        </p>
                                        {% endif %}
    
                                    {% endfor %}
                                
                            </div>
                        </div>
                    {% else %}
                        <p>No reminders set yet</p>
                    {% endif %}
                    {% if can_edit %}
                        <a href="{% url 'reminder_add' action_item.id %}">Edit/Add reminder</a>
                    {% endif %}
                </div>
                <div class="panel-footer">
                    <small>
                    Last modified: {{ action_item.last_modified_date|date:"j M Y" }} - 
                    Published: {{ action_item.published_date|date:"j M Y" }} - 
                    Created by {{ action_item.creator.username }}
                    {% if can_edit and action_item.status in status_show_close_btn %}
                    - <a href="{% url 'action_item_edit' action_item.id %}" class="btn btn-sm btn-warning">Edit action item</a>
                    {% endif %}
                    {% if can_edit and action_item.status in status_show_close_btn %}
                    - <a href='{% url "action_item_close" action_item.id %}' class="btn btn-sm btn-danger">Close action item?</a>
                    {% endif %}
                    {% if can_propose_close and action_item.status in status_show_propose_close_btn %}
                    - <a href='{% url "action_item_propose_close" action_item.id %}' class="btn btn-sm btn-info">Propose close action item?</a>
                    {% endif %}
                    </small>
                </div>
            </div>
    </div>

    </div>

            <div class="col-md-4">
                <div class="section">
                        <h3>Updates/Remarks</h3>
                        <ul class="list-group">
                            {% for update in updates %}
                                <li class="list-group-item">
                                    <p>{{ update.text }}</p>
                                    <small>submitted on {{ update.published_date|date:"jS M Y P" }} by {{ update.user.profile.full_name }}
                                    {% if request.user == update.user %}
                                        <a href="{% url 'update_delete' action_item.id update.id %}" class="text-danger">Delete</a>
                                    {% endif %}</small>
                                </li>
                            {% empty %}
                                <li class="list-group-item">No updates/remarks for now.</li>
                            {% endfor %}
                        </ul>
                        {% if form %}
                            {% load crispy_forms_tags %}
                            {% crispy form %}             
                        {% else %}
                            <small>Only action item initiator, owner and assingee can add update/remarks</small>
                        {% endif %}
                </div>

            </div>


</div>

{% else %}
    <p>Wrong page, please click here to go back to <a href="{% url 'action_item_index' %}"></a></p>
{% endif %}

{% endblock main %}


{% block js %}
<script>
        $("#id_text").val("")
</script>
{% endblock js %}

actionitems/templates/actionitems/action_item_close.html
{% extends "actionitems/base.html" %}

{% block main %}
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        {% if action_item %}
        <ul class="list-group">
            <li class="list-group-item">
                <h3>{{ action_item.title }}</h3>
            </li>
        </ul>
        <p>Confirm to close the action item and remove all future reminder?</p>
        <form method="post">
            {% csrf_token %}
            <a href="{% url 'action_item' action_item.id %}" class="btn btn-default">No, take me back</a>
            <input type="submit" value="Yes, close the Action Item" class="btn btn-danger">
        </form>

        {% else %}
        <p>Error, no action item found</p>
        {% endif %}
    </div>
</div>


{% endblock main %}

{% block js %}

{% endblock js %}

actionitems/templates/actionitems/action_item_create.html
{% extends "actionitems/base.html" %}

{% block main %}

{% if templates %}
    <h3>Select action item template: </h3>
    <div class="list-group">
        {% for template in templates %}
            <a href="{% url 'action_item_create' template.id %}" class="list-group-item">
                <h4>{{ template.name }}</h4>
                <p>{{ template.description }}</p>
            </a>
        {% endfor %}
    </div>

{% else %}
<div class="col-md-8 col-md-offset-2">

    <h3>Create new action item</h3>
    <p> {{ template.name }} </p>
    <hr>
    {% load crispy_forms_tags %}
    {% crispy form %} 

</div>


{% endif %}




{% endblock main %}

{% block js %}

<script type="text/javascript">
    function datepicker(){
        $("div.alpaca-field-date > input.alpaca-control").flatpickr();
    }

    $("#details").alpaca({
        "schema": {{ schema|safe }},
        "options": {{ options|safe }},
        "postRender": function(control) {
            if(control.childrenByPropertyId['assessment-date'] !== undefined ){
                control.childrenByPropertyId['assessment-date'].on("load", datepicker() );
            }
        }
    });        


    $("#id_due_date").flatpickr({
        "enable": [{
                from:new Date(),
                to: "3000-12-31"
        }]
     });

    $('.selectpicker').selectpicker({
        liveSearch: true
    })

</script>

{% endblock js %}

actionitems/templates/actionitems/advance_list.html
{% extends "actionitems/base.html" %}

{% block main %}

<div class="section">
        {% if action_items %}
        <h1>My Action Item</h1>
        <table id="indexTable" class="table table-hover">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Class.</th>
                    <th>Status</th>
                    <th>Due</th>
                    <th>Dept</th>
                    <th>Initiator</th>
                    <th>Owner</th>
                    <th>Assignee</th>
                    <th>Template</th>
                </tr>
            </thead>
            <tbody>
                {% for action_item in action_items %}
                
                <tr class="clickable-row" data-href="{% url 'action_item' action_item.id %}">
                    <td><a href="{% url 'action_item' action_item.id %}">{{ action_item.title }}</a></td>
                    <td>{{ action_item.get_classification_display }}</td>
                    {% if action_item.status == "OPEN" %}
                        <td class="bg-warning">{{ action_item.get_status_display }}</td>
                    {% elif action_item.status == "OVERDUE"  %}
                        <td class="bg-danger">{{ action_item.get_status_display }}</td>
                    {% elif action_item.status == "PROPOSE-CLOSE"  %}
                        <td class="bg-info">{{ action_item.get_status_display }}</td>
                    {% elif action_item.status == "COMPLETED"  %}
                        <td class="bg-success">{{ action_item.get_status_display }}</td>
                    {% endif %}
                    <td>{{ action_item.due_date|date:"Y-m-t" }}</td>
                    <td>{{ action_item.department.name }}</td>
                    <td>
                        {% for i in action_item.initiator.all %} {{ i.profile.full_name }}, {% endfor %}
                    </td>
                    <td>
                        {% for i in action_item.owner.all %} {{ i.profile.full_name }}, {% endfor %}
                    </td>
                    <td>
                        {% for i in action_item.assignee.all %} {{ i.profile.full_name }}, {% endfor %}
                    </td>
                    <td>{{ action_item.template.name }}</td>
                </tr>
                {% endfor %}
    
            </tbody>
        </table>
    
        {% else %}
            <p>No action items found</p>
        {% endif %}
    </div>

{% endblock main %}

{% block js %}
<script>
        $('#indexTable').DataTable({
            responsive: true,
            dom: 'Bfrtip',
            buttons: [
            'copy', 'excel', 'pdf'
            ]
        });
</script>

{% endblock js %}

actionitems/templates/actionitems/list.html
{% extends "actionitems/base.html" %}

{% block main %}

<div class="section">
        {% if action_items %}
        <h1>{{ status|capfirst }} Action Items as {{ as_a|capfirst }}</h1>
        <table id="indexTable" class="table table-hover">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Class.</th>
                    <th>Status</th>
                    <th>Due</th>
                    <th>Dept</th>
                    <th>Initiator</th>
                    <th>Owner</th>
                    <th>Assignee</th>
                    <th>Template</th>
                </tr>
            </thead>
            <tbody>
                {% for action_item in action_items %}
                
                <tr class="clickable-row" data-href="{% url 'action_item' action_item.id %}">
                    <td><a href="{% url 'action_item' action_item.id %}">{{ action_item.title }}</a></td>
                    <td>{{ action_item.get_classification_display }}</td>
                    {% if action_item.status == "OPEN" %}
                        <td class="bg-warning">{{ action_item.get_status_display }}</td>
                    {% elif action_item.status == "OVERDUE"  %}
                        <td class="bg-danger">{{ action_item.get_status_display }}</td>
                    {% elif action_item.status == "PROPOSE-CLOSE"  %}
                        <td class="bg-info">{{ action_item.get_status_display }}</td>
                    {% elif action_item.status == "COMPLETED"  %}
                        <td class="bg-success">{{ action_item.get_status_display }}</td>
                    {% endif %}
                    <td>{{ action_item.due_date|date:"Y-m-t" }}</td>
                    <td>{{ action_item.department.name }}</td>
                    <td>
                        {% for i in action_item.initiator.all %} {{ i.profile.full_name }}, {% endfor %}
                    </td>
                    <td>
                        {% for i in action_item.owner.all %} {{ i.profile.full_name }}, {% endfor %}
                    </td>
                    <td>
                        {% for i in action_item.assignee.all %} {{ i.profile.full_name }}, {% endfor %}
                    </td>
                    <td>{{ action_item.template.name }}</td>
                </tr>
                {% endfor %}
    
            </tbody>
        </table>
    
        {% else %}
            <p>No action items found</p>
        {% endif %}
    </div>

{% endblock main %}

{% block js %}
<script>
        $('#indexTable').DataTable({
            responsive: true,
            dom: 'Bfrtip',
            buttons: [
            'copy'
            ]
        });
</script>

{% endblock js %}